:Author: yaruko
:Email:
:Date: 21/04/2024
:Revision: version#
:License: Public Domain

= Project: Aquecedor de animais de pequeno porte IoT

Projeto para controle de temeperatura de viveiros por meio do sensor DHT11 e ESP32 

== Step 1: Installation
Instalar bibliotecas referentes ao DHT11
Instalar bibliotecas relacionadas com o Arduino IoT
Preferencialmente utilize a plataforma Arduino IoT pois instala automaticamente os itens descritos

== Step 2: Assemble the circuit

Realize a conexão baseada no código ou altere a pinagem a sua preferência
Não esquecer do resistor pulldown para a chave magnética

== Step 3: Load the code

Utilizando o Arduino Manage Agent (instalar para realizar Upload via plataforma) pode-se realizar o upload do código por meio de uma 
entrada Micro-USB

== Folder structure

....
 AquecedorPassaro_apr21a       => Arduino sketch folder
  ├── AquecedorPassaro_apr21a.ino       => main Arduino file
  ├── esquema.png      => (optional) an image of the required schematics
  ├── thingProperties.h => Configurações do ArduinoCloud

== Contributing
To contribute to this project please contact: 
rafael.kenji@Uunesp.br

== BOM
O que vc vai precisar:

|===
| Part name         | Quantity |
| 10k Resistor      | 1        |
| Rele 5V           | 1        |
| ESP32 DevKit V1   | 1        |
| Sensor Magnético  | 1        |
| Sensor DHT11      | 1        |        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
