// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f9187a9f-c77f-46fb-b5fb-d4d3e1281360";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onReleChange();
void onTempDesejadaChange();

CloudSwitch rele;
CloudTemperatureSensor temperatura;
CloudRelativeHumidity umidade;
bool estadoPorta;
CloudTemperature tempDesejada;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(rele, READWRITE, ON_CHANGE, onReleChange);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(umidade, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(estadoPorta, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempDesejada, READWRITE, ON_CHANGE, onTempDesejadaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
